In [1]:
import pandas as pd

In [2]:
data = {
    'Name' : ['John', 'Jane', 'Bob', 'Alice'],
    'Age' : [25, 30, 35, 40],
    'City' : ['New York', 'Paris', 'London', 'Sydney']
}

print(data)

{'Name': ['John', 'Jane', 'Bob', 'Alice'], 'Age': [25, 30, 35, 40], 'City': ['New York', 'Paris', 'London', 'Sydney']}

In [3]:
for key, value in data.items():
  print(f"{key}: {value}")

Name: ['John', 'Jane', 'Bob', 'Alice']
Age: [25, 30, 35, 40]
City: ['New York', 'Paris', 'London', 'Sydney']

In [4]:
df = pd.DataFrame(data)
print(df)

    Name  Age      City
0   John   25  New York
1   Jane   30     Paris
2    Bob   35    London
3  Alice   40    Sydney

In [5]:
dataset = pd.read_csv('Data.csv')
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [6]:
dataset.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,9.0,38.777778,7.693793,27.0,35.0,38.0,44.0,50.0
Salary,9.0,63777.777778,12265.579662,48000.0,54000.0,61000.0,72000.0,83000.0

In [7]:
dataset.describe(include = 'O').T

          count unique     top freq
Country      10      3  France    4
Purchased    10      2      No    5

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('unique').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('top').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('freq').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['top'].value_counts()
    for x_label, grp in _df_3.groupby('unique')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('unique')
_ = plt.ylabel('top')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['freq'].value_counts()
    for x_label, grp in _df_4.groupby('top')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('top')
_ = plt.ylabel('freq')

In [8]:
df = pd.DataFrame(data)
print(df)

    Name  Age      City
0   John   25  New York
1   Jane   30     Paris
2    Bob   35    London
3  Alice   40    Sydney

In [9]:
df['Age']

0    25
1    30
2    35
3    40
Name: Age, dtype: int64

In [27]:
#.iloc and loc [row : column]
#',' for indivisual value
#':' for range value
df.iloc[[0,2] ,[0,1]]

   Name  Age
0  John   25
2   Bob   35

In [25]:
df.loc[2, 'Name'] #loc we use as column name

'Bob'

Filtering Data

In [28]:
df

    Name  Age      City
0   John   25  New York
1   Jane   30     Paris
2    Bob   35    London
3  Alice   40    Sydney

In [29]:
df[df['Age']> 32]

    Name  Age    City
2    Bob   35  London
3  Alice   40  Sydney

Modifying

In [31]:
df['Age'] = df['Age'] +10
df

    Name  Age      City
0   John   45  New York
1   Jane   50     Paris
2    Bob   55    London
3  Alice   60    Sydney

In [52]:
df['Wife'] = ['Sandra', 'Alice', 'Charliee', 'Astra']
df

    Name  Age      Wife
0   John   45    Sandra
1   Jane   50     Alice
2    Bob   55  Charliee
3  Alice   60     Astra

In [55]:
df.drop(columns = ['Wife'])

    Name  Age
0   John   45
1   Jane   50
2    Bob   55
3  Alice   60

In [63]:
df['Wife'] = ['Sandra', 'Alice', 'Charliee', 'Astra']
df['Salary'] = [50000, 60000, 70000, 80000]

In [56]:
dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [59]:
dataset.groupby('Country')['Age'].mean()

Country
France     41.0
Germany    40.0
Spain      32.5
Name: Age, dtype: float64

In [64]:
df.to_csv('New.csv')

In [73]:
df['Salary'].apply(lambda x:x**2),

(0    2500000000
 1    3600000000
 2    4900000000
 3    6400000000
 Name: Salary, dtype: int64,)

In [74]:
df.set_index('Salary', inplace = True)

In [75]:
df

         Name  Age      Wife
Salary
50000    John   45    Sandra
60000    Jane   50     Alice
70000     Bob   55  Charliee
80000   Alice   60     Astra

In [76]:
data = {
    'Name' : ['John', 'Jane', 'Bob', 'Alice'],
    'Age' : [25, 30, 35, 40],
    'City' : ['New York', 'Paris', 'London', 'Sydney']
}

df = pd.DataFrame(data)

In [78]:
df2 = {
    'New Name' : ['Larry', 'Barry', 'Carter', 'Holly'],
    'Age' : [25, 30, 35, 40],
    'City' : ['New York', 'Paris', 'London', 'Sydney']
}
df2 = pd.DataFrame(df2)

In [81]:
pd.merge(df,df2,on = 'Age')

    Name  Age    City_x New Name    City_y
0   John   25  New York    Larry  New York
1   Jane   30     Paris    Barry     Paris
2    Bob   35    London   Carter    London
3  Alice   40    Sydney    Holly    Sydney